#3.4 Guest list
guest_list = ['Taylor Swift', 'Lucy Bronze', 'David Beckham']
print (guest_list)
invite_message = " you are invited to a dinner party."
print (guest_list[0] + invite_message)
print (guest_list[1] + invite_message)
print (guest_list[2] + invite_message)
popped_guests = guest_list.pop(0)
print (guest_list)
print (popped_guests)
guest_list.insert  (0, "Alex Morgan")
print (guest_list)
print (guest_list[0] + invite_message)
print (guest_list[1] + invite_message)
print (guest_list[2] + invite_message)
guest_list.insert (0, "Megan Rapinoe")
guest_list.insert (3, "Keria Walsh")
guest_list.append ("Phil Neville")
print (guest_list)
print (guest_list[0] + invite_message)
print (guest_list[1] + invite_message)
print (guest_list[2] + invite_message)
print (guest_list[3] + invite_message)
print (guest_list[4] + invite_message)
print (guest_list[5] + invite_message)
print ("Only two guest allowed now")
guest_list.pop(5)
guest_list.pop(3)
guest_list.pop(0)
guest_list.pop(0)
print (guest_list)
print (guest_list[0] + ' and ' + guest_list[1] + invite_message)
